
language: python


matrix:
  include:
    - python: 2.7
      env: FLOATX=float32
# Setup Python environment with BLAS libraries
before_install:

  - wget -q http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  - conda update -q --yes conda
  - export FUEL_DATA_PATH=$TRAVIS_BUILD_DIR/data



install:
  - pip install .
  - pip2 install theano
  - pip2.7 install theano
  - pip install -r requirements.txt
  - python setup.py install

# command to run tests
script: nosetests